project:
  type: website

website:
  title: "demosite"
  navbar:
    foreground: white
    background: primary
    right:
      - text: "Posts"
        file: blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: [sketchy, theme.scss]
    css: styles.css



